# Generated by Django 5.1.7 on 2025-05-05 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_useraddress_userorder_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='orderid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.userorder'),
        ),
    ]
